### ISSUE TITLE
Issue accessing container

### ISSUE THREAD

**Issue by ashwinjoseph95** [ika-rwth-aachen/acdc#15]
Hi,
I was following the instructions on edX to set up the acdc repository on my Ubuntu 20.04LTS OS 
I am able to execute the first run of` /ros1_run.sh.` but the second run to access the container somehow does not work as expected. Have attached the screenshot below for your reference:
![Screenshot from 2023-10-19 15-17-03](https://github.com/ika-rwth-aachen/acdc/assets/30999857/9a7d927e-f020-4bf2-93c5-47e181417464)
Could you help me troubleshoot this issue, as per the MOOC page I should be able to directly enter the container after running it without any further modifications in the sh file.

**Comment by TillBeemelmanns** [comment]
Hi, we did a little fix on the run scripts recently. Could you please pull the acdc (`git pull`) repository again and try again ?

**Comment by ashwinjoseph95** [comment]
Yes, its fixed now after the pull. Thank you
