### ISSUE TITLE
Problem in running ./ros1_run.sh

### ISSUE THREAD

**Issue by arshemii** [ika-rwth-aachen/acdc#17]
> Thanks for creating an issue, we will support you as soon as possible.  
> Please fill out the issue template below by answering **all** questions.

1. **Are you using a virtual machine or are you using native Ubuntu?**

On Virtual Machine (vmware)

2. **If you are using macOS and a virtual machine, does your computer use an M1, M2, ... chip?** "Does not apply" if the question does not apply to you.

YOUR ANSWER 

3. **Which Ubuntu version are you using?** (`lsb_release -a` in a terminal)

ubuntu 22.04.3 LTS

4. **On your host, in a terminal, navigate to the acdc repository and execute `ls -la` and paste the content here.**

total 56
drwxrwxr-x 9 arash arash 4096 ott 28 20:47 .
drwxrwxr-x 3 arash arash 4096 ott 28 20:45 ..
drwxrwxr-x 2 arash arash 4096 ott 28 20:47 assets
drwxrwxr-x 2 arash arash 4096 ott 28 20:47 bag
drwxrwxr-x 3 arash arash 4096 ott 28 20:47 catkin_workspace
drwxrwxr-x 3 arash arash 4096 ott 28 20:47 colcon_workspace
drwxrwxr-x 2 arash arash 4096 ott 28 20:47 docker
drwxrwxr-x 9 arash arash 4096 ott 28 20:47 .git
drwxrwxr-x 4 arash arash 4096 ott 28 20:47 .github
-rwxrwxr-x 1 arash arash 2761 ott 28 20:47 .gitignore
-rwxrwxr-x 1 arash arash 2001 ott 28 20:47 .gitlab-ci.yml
-rwxrwxr-x 1 arash arash  833 ott 28 20:47 .gitmodules
-rwxrwxr-x 1 arash arash 1104 ott 28 20:47 LICENSE
-rwxrwxr-x 1 arash arash 2816 ott 28 20:47 README.md

5. **On your host, in a terminal, navigate to the `catkin_workspace` folder in the acdc repository and execute `ls -la` and paste the content here.**

total 16
drwxrwxr-x 3 arash arash 4096 ott 28 20:47 .
drwxrwxr-x 9 arash arash 4096 ott 28 20:47 ..
-rw-rw-r-- 1 arash arash   98 ott 28 20:47 .catkin_workspace
-rw-rw-r-- 1 arash arash    0 ott 28 20:47 .gitkeep
drwxrwxr-x 4 arash arash 4096 ott 28 20:47 src

6. **On your host, execute `docker images` and paste the content here.**

REPOSITORY     TAG       IMAGE ID       CREATED        SIZE
rwthika/acdc   ros1      b4c4c4abd17a   2 weeks ago    23.8GB
hello-world    latest    9c7a54a9a43c   5 months ago   13.3kB

7. **Briefly explain your problem here. The explanation should contain a description of the expected behavior and the actual behavior.**

After running the command "docker pull rwthika/acdc:ros1" in my host in terminal, and waiting for downloading all, I want to execute ./ros1_run.sh (Naturally I navigate to the repository .../acdc/docker/ ), but the error I have is: Starting new container 'acdc_ros1' ...
================================================================================

docker: invalid reference format.
See 'docker run --help'.

8. **If you got an error message, paste it here or post a screenshot of it.**

**Error Message:**
Starting new container 'acdc_ros1' ...
================================================================================

docker: invalid reference format.
See 'docker run --help'.

**Screenshot:**
INSERT HERE

**Comment by TillBeemelmanns** [comment]
Hi arshemii,

it's not possible for me to reproduce your error. 

- Did you change any of the files belonging to the acdc repository ?
- Did you change the files `ros1_run.sh` or `ros2_run.sh` ?
- What is the output of `git status` when you execute this command in the acdc repository ?
- Can you make sure that you have the latest version of the code by executing `git pull` ?
- Have you installed `docker-run` successfully ? Please check the installation guide here https://github.com/ika-rwth-aachen/docker-run#installation

Bests,
Till

**Comment by arshemii** [comment]
> Hi arshemii,
> 
> it's not possible for me to reproduce your error.
> 
> * Did you change any of the files belonging to the acdc repository ?
> * Did you change the files `ros1_run.sh` or `ros2_run.sh` ?
> * What is the output of `git status` when you execute this command in the acdc repository ?
> * Can you make sure that you have the latest version of the code by executing `git pull` ?
> * Have you installed `docker-run` successfully ? Please check the installation guide here https://github.com/ika-rwth-aachen/docker-run#installation
> 
> Bests, Till

Hello. Thanks for the answer. The problem has been solved, I dont know how, but I reinstall everything again. 
Anyway, thanks again
