### ISSUE TITLE
Command to clone ACDC repository is not working

### ISSUE THREAD

**Issue by ARLAB-2018** [ika-rwth-aachen/acdc#2]
```git clone --recurse-submodules git@github.com:ika-rwth-aachen/acdc.git```

Command no working and showing.
```
Cloning into 'acdc'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by bastilam** [comment]
Please try `git clone --recurse-submodules https://github.com/ika-rwth-aachen/acdc.git` and let me know whether this works for you.

**Comment by ARLAB-2018** [comment]
Yeah this one worked. Thank you for the help.
