### ISSUE TITLE
While running rosservice info /move_model  , got some errors

### ISSUE THREAD

**Issue by parasmech** [ika-rwth-aachen/acdc#3]
> Thanks for creating an issue, we will support you as soon as possible.  
> Please fill out the issue template below by answering **all** questions.

1. **Are you using a virtual machine or are you using native Ubuntu?**

native Ubuntu

2. **If you are using macOS and a virtual machine, does your computer use an M1, M2, ... chip?** "Does not apply" if the question does not apply to you.

Does not apply 

3. **Which Ubuntu version are you using?** (`lsb_release -a` in a terminal)

Ubuntu 22.04.1 LTS

4. **On your host, in a terminal, navigate to the acdc repository and execute `ls -la` and paste the content here.**

total 56
drwxrwxr-x 9 parasubu parasubu 4096 Dec 10 14:09 .
drwxr-xr-x 3 parasubu parasubu 4096 Dec 10 15:49 ..
drwxrwxr-x 2 parasubu parasubu 4096 Dec 10 14:09 assets
drwxrwxr-x 2 parasubu parasubu 4096 Dec 10 14:09 bag
drwxrwxr-x 7 parasubu parasubu 4096 Dec 11 19:06 catkin_workspace
drwxrwxr-x 3 parasubu parasubu 4096 Dec 10 14:09 colcon_workspace
drwxrwxr-x 2 parasubu parasubu 4096 Dec 10 14:09 docker
drwxrwxr-x 9 parasubu parasubu 4096 Dec 10 14:09 .git
drwxrwxr-x 4 parasubu parasubu 4096 Dec 10 14:09 .github
-rw-rw-r-- 1 parasubu parasubu 2656 Dec 10 14:09 .gitignore
-rw-rw-r-- 1 parasubu parasubu 2001 Dec 10 14:09 .gitlab-ci.yml
-rw-rw-r-- 1 parasubu parasubu  659 Dec 10 14:09 .gitmodules
-rw-rw-r-- 1 parasubu parasubu 1104 Dec 10 14:09 LICENSE
-rw-rw-r-- 1 parasubu parasubu 1297 Dec 10 14:09 README.md

5. **On your host, in a terminal, navigate to the `catkin_workspace` folder in the acdc repository and execute `ls -la` and paste the content here.**

total 32
drwxrwxr-x  7 rosuser rosuser 4096 Dec 11 19:06 .
drwxrwxr-x  9 rosuser rosuser 4096 Dec 10 14:09 ..
drwxrwxr-x  3 rosuser rosuser 4096 Dec 11 19:06 .catkin_tools
-rw-rw-r--  1 rosuser rosuser   98 Dec 10 14:09 .catkin_workspace
-rw-rw-r--  1 rosuser rosuser    0 Dec 10 14:09 .gitkeep
drwxrwxr-x 35 rosuser rosuser 4096 Dec 11 19:12 build
drwxrwxr-x  7 rosuser rosuser 4096 Dec 11 19:09 devel
drwxrwxr-x 35 rosuser rosuser 4096 Dec 11 19:12 logs
drwxrwxr-x  4 rosuser rosuser 4096 Dec 10 14:09 src

6. **On your host, execute `docker images` and paste the content here.**

parasubu@parasubu-Vostro-15-3510:~/Downloads/acdc/docker$ sudo ./run.sh 
[sudo] password for parasubu: 
Attaching to running container ...
  Name: ros
  Image: rwthika/acdc:latest

=== ROS Docker Container =======================================================

Container setup:
- Ubuntu: 20.04.4 LTS (Focal Fossa) (user: rosuser, password: rosuser)
- Architecture: x86_64
- CUDA: 11.2.152
- cuDNN: 8.1.0
- TensorRT: 7.2.2
- Python: 3.8.10
- TensorFlow Python: 2.8.0
- TensorFlow C/C++: 2.8
- ROS: noetic
- CMake: 3.16.3

Available GPUs: 0

Template Commands: (https://gitlab.ika.rwth-aachen.de/automated-driving/docker#templates)
- Create new ROS package:            ros-add-package
  - Add node to package:               ros-add-node
  - Add nodelet to package:            ros-add-nodelet
- Initialize ROS GitLab repository:  ros-init-repo

7. **Briefly explain your problem here. The explanation should contain a description of the expected behavior and the actual behavior.**

Working on ROS - Foundations.
While running rosservice info /move_model  , got some errors
After this error, other commands are also not working

8. **If you got an error message, paste it here or post a screenshot of it.**

**Error Message:**
rosuser@parasubu-Vostro-15-3510:~/ws/catkin_workspace$ rosservice info /move_model
Node: /flatland_server
URI: rosrpc://parasubu-Vostro-15-3510:43449
Type: flatland_msgs/MoveModel
ERROR: Unable to load type [flatland_msgs/MoveModel].
Have you typed 'make' in [flatland_msgs]?

![image](https://user-images.githubusercontent.com/50964242/207273009-40386cd3-1527-4f5d-9b84-522463c7a50a.png)

**Comment by TillBeemelmanns** [comment]
This error message indicates that the `flatland_msgs/MoveModel` message type is not available on the system. It is likely that the `flatland_msgs` package has not been built using the `catkin build` command. In order to fix this error, you can try to run the `catkin build flatland_msgs` command. This will build the package and make the `flatland_msgs/MoveModel` message type available. Make sure to source the workspace again in all your terminals after building it.

**Comment by parasmech** [comment]
Thanks for the help. It worked now as per your instructions
