### ISSUE TITLE
catkin build error

### ISSUE THREAD

**Issue by Suchit153** [ika-rwth-aachen/acdc#4]
> Thanks for creating an issue, we will support you as soon as possible.  
> Please fill out the issue template below by answering **all** questions.

1. **Are you using a virtual machine or are you using native Ubuntu?**

native Ubuntu

2. **If you are using macOS and a virtual machine, does your computer use an M1, M2, ... chip?** "Does not apply" if the question does not apply to you.

YOUR ANSWER 

3. **Which Ubuntu version are you using?** (`lsb_release -a` in a terminal)

22.04.1 LTS (Jammy)

4. **On your host, in a terminal, navigate to the acdc repository and execute `ls -la` and paste the content here.**

PASTE HERE

5. **On your host, in a terminal, navigate to the `catkin_workspace` folder in the acdc repository and execute `ls -la` and paste the content here.**

total 56
drwxrwxr-x  9 suchit suchit 4096 Nov  4 22:55 .
drwxr-x--- 70 suchit suchit 4096 Dez 13 00:16 ..
drwxrwxr-x  2 suchit suchit 4096 Nov  4 22:55 assets
drwxrwxr-x  2 suchit suchit 4096 Dez 12 22:25 bag
drwxrwxr-x  7 suchit suchit 4096 Dez 13 12:57 catkin_workspace
drwxrwxr-x  6 suchit suchit 4096 Nov 17 20:01 colcon_workspace
drwxrwxr-x  2 suchit suchit 4096 Nov  4 22:55 docker
drwxrwxr-x  9 suchit suchit 4096 Dez 13 00:17 .git
drwxrwxr-x  4 suchit suchit 4096 Nov  4 22:55 .github
-rw-rw-r--  1 suchit suchit 2656 Nov  4 22:55 .gitignore
-rw-rw-r--  1 suchit suchit 2001 Nov  4 22:55 .gitlab-ci.yml
-rw-rw-r--  1 suchit suchit  659 Nov  4 22:55 .gitmodules
-rw-rw-r--  1 suchit suchit 1104 Nov  4 22:55 LICENSE
-rw-rw-r--  1 suchit suchit 1297 Nov  4 22:55 README.md

6. **On your host, execute `docker images` and paste the content here.**

REPOSITORY     TAG       IMAGE ID       CREATED         SIZE
rwthika/acdc   latest    82e604df3cde   2 months ago    23.7GB
hello-world    latest    feb5d9fea6a5   14 months ago   13.3kB

7. **Briefly explain your problem here. The explanation should contain a description of the expected behavior and the actual behavior.**

catkin build produces an error as shown below. catkin clean command does not solve the issue.

8. **If you got an error message, paste it here or post a screenshot of it.**

**Error Message:**
PASTE HERE

**Screenshot:**
![Screenshot from 2022-12-13 12-57-32](https://user-images.githubusercontent.com/66416823/207326304-af9b8cd5-e052-4498-8acb-b44fd726b344.png)

**Comment by TillBeemelmanns** [comment]
I can't really reproduce your problem and the error message is ambiguous. 

Make sure that the directories 

- `/home/rosuser/ws/catkin_workspace/build`
- `/home/rosuser/ws/catkin_workspace/devel`
- `/home/rosuser/ws/catkin_workspace/logs`

are completely removed after `catkin clean`.

Does `catkin build -v` help if you use it instead of `catkin build` ?

**Comment by Suchit153** [comment]
no, unfortunately `catkin build -v`does not help. The same error persists.
Could you please tell me how I can delete the `rwthika/acdc` docker image and pull it again on my system?

**Comment by TillBeemelmanns** [comment]
The command to remove the image would be `docker rmi rwth/acdc`.

I am not sure if the is the cause for you problems, since everyone else is also using the exact same docker image. And I don't think you can change anything of the docker image. 

Did you alter any files in the repository, except the exercises ? Maybe you can go to the directory `acdc` (in your terminal, outside of docker) and execute `git diff` and paste the response here.

**Comment by Suchit153** [comment]
no change as far as I see 
![Screenshot from 2022-12-13 17-17-29](https://user-images.githubusercontent.com/66416823/207386497-1cfbcafb-f031-46b0-9a9f-f6f78c3073ae.png)

**Comment by Suchit153** [comment]
Could you please confirm if my git config is correct. I tried to push the repo to my remote branch yesterday. That might be the issue. 
![Screenshot from 2022-12-13 17-20-03](https://user-images.githubusercontent.com/66416823/207387368-fe8d64c2-58c2-4830-a0d4-bec11ab2073b.png)
![Screenshot from 2022-12-13 17-18-25](https://user-images.githubusercontent.com/66416823/207387373-48739c8c-cab2-43cc-800e-52b521361095.png)

**Comment by TillBeemelmanns** [comment]
This could be a problem. However you haven't pushed anything, your repository https://github.com/Suchit153/acdc is completely empty. The A better way would be to fork https://github.com/ika-rwth-aachen/acdc and work on the work. I can't see what you have committed in these 3 commits.

Try to do a second unspoiled clone of the acdc repository 
```git clone --recurse-submodules https://github.com/ika-rwth-aachen/acdc.git ~/acdc2```
And try to compile the workspace in the new acdc repository. If that succeeds, than your repository and workspace in `~/acdc` is messed up.

**Comment by Suchit153** [comment]
yes, I removed and recloned the git repo, this time with a fork to my repository. It worked!
