### ISSUE TITLE
Sensitive Case Error

### ISSUE THREAD

**Issue by mahapathak** [ika-rwth-aachen/acdc#8]
> Thanks for creating an issue, we will support you as soon as possible.  
> Please fill out the issue template below by answering **all** questions.

1. **Are you using a virtual machine or are you using native Ubuntu?**

Windows with Powershell My computer supports Ws1

2. **If you are using macOS and a virtual machine, does your computer use an M1, M2, ... chip?** "Does not apply" if the question does not apply to you.

YOUR ANSWER 

3. **Which Ubuntu version are you using?** (`lsb_release -a` in a terminal)

PASTE HERE

4. **On your host, in a terminal, navigate to the acdc repository and execute `ls -la` and paste the content here.**

    Directory: C:\Windows\system32\Documents

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----          9/2/2023   3:37 PM                acdc

5. **On your host, in a terminal, navigate to the `catkin_workspace` folder in the acdc repository and execute `ls -la` and paste the content here.**

PASTE HERE

6. **On your host, execute `docker images` and paste the content here.**

PASTE HERE

7. **Briefly explain your problem here. The explanation should contain a description of the expected behaviour and the actual behaviour.**

I was following steps from the GitHub instructions for the Setup ROS Coding Environment using Windows WSL2 which needs to check first whether the system supports WS1 or not. I have checked it with the given commands everything was fine. But when I typed "cd Documents" The system did not find the folder so I manually created a document folder with the path "C:\Windows\System32\Documents" After that it stated that I needed to add case sensitive command but when I tried to enter the command showed me "PS C:\Windows\system32\Documents> fsutil.exe file setCaseSensitiveInfo acdc enable
Error: Setting case sensitive attribute on C:\Windows\system32\Documents\acdc is not supported."
8. **If you got an error message, paste it here or post a screenshot of it.**

**Error Message:**
PASTE HERE

**Screenshot:**
INSERT HERE
![A](https://github.com/ika-rwth-aachen/acdc/assets/124674149/6a5a0984-0915-4b60-86d5-0c97c14eb31c)

**Comment by TillBeemelmanns** [comment]
Hi,

can you check some of the following resource. Either you need to update your system including WSL or you need to enable the case sensitive feature.

- https://stackoverflow.com/questions/50839623/fsutil-the-request-is-not-supported-after-setcasesensitiveinfo
- https://learn.microsoft.com/en-us/windows/wsl/case-sensitivity


Bests,
Till

**Comment by TillBeemelmanns** [comment]
Closed due to inactivity. Feel free to reopen if necessary.

**Comment by mahapathak** [comment]
Respected sir/madam,

Thank you for the response I would like to add that I have resolved the
error.

Thank you so much.

Regards,
Maharshi Pathak

**Comment by M-Tarakji** [comment]
Hi @TillBeemelmanns,

I would like to re-open this issue back up as I'm facing the same problem using the same setup. I created the Documents directory, tried to enable the case sensitivity resulting in the same error (in German). Unfortunately both solutions described in the provided links did not solve the issue for me.

I tried enabling "optional features" as described on Stackoverflow as well as creating a wsl.conf with the respective settings in Ubuntu as prescribed by the Microsoft documentation.

Do you have any other Idea what the issue/solution is?

much appreciated!
Mouhidin

![image](https://github.com/user-attachments/assets/44c35ade-a6ed-4c0e-94a9-adf594ee4c10)
