### ISSUE TITLE
rqt, rviz not working as expected

### ISSUE THREAD

**Issue by Adharshmahesh** [ika-rwth-aachen/acdc#9]
> Thanks for creating an issue, we will support you as soon as possible.  
> Please fill out the issue template below by answering **all** questions.

1. **Are you using a virtual machine or are you using native Ubuntu?**
I am using wsl2 using a windows machine

2. **If you are using macOS and a virtual machine, does your computer use an M1, M2, ... chip?** "Does not apply" if the question does not apply to you.

DNA

3. **Which Ubuntu version are you using?** (`lsb_release -a` in a terminal)

Ubuntu 20.04.6 LTS

4. **On your host, in a terminal, navigate to the acdc repository and execute `ls -la` and paste the content here.**

total 16
drwxrwxrwx 1 adharsh adharsh 4096 Sep  4 14:56 .
drwxrwxrwx 1 adharsh adharsh 4096 Sep  4 14:56 ..
drwxrwxrwx 1 adharsh adharsh 4096 Sep  4 14:56 .git
drwxrwxrwx 1 adharsh adharsh 4096 Sep  4 14:55 .github
-rwxrwxrwx 1 adharsh adharsh 2656 Sep  4 14:55 .gitignore
-rwxrwxrwx 1 adharsh adharsh 2001 Sep  4 14:55 .gitlab-ci.yml
-rwxrwxrwx 1 adharsh adharsh  659 Sep  4 14:55 .gitmodules
-rwxrwxrwx 1 adharsh adharsh 1104 Sep  4 14:55 LICENSE
-rwxrwxrwx 1 adharsh adharsh 2422 Sep  4 14:55 README.md
drwxrwxrwx 1 adharsh adharsh 4096 Sep  4 14:55 assets
drwxrwxrwx 1 adharsh adharsh 4096 Sep  4 14:55 bag
drwxrwxrwx 1 adharsh adharsh 4096 Sep  4 14:55 catkin_workspace
drwxrwxrwx 1 adharsh adharsh 4096 Sep  4 14:56 colcon_workspace
drwxrwxrwx 1 adharsh adharsh 4096 Sep  4 14:56 docker

5. **On your host, in a terminal, navigate to the `catkin_workspace` folder in the acdc repository and execute `ls -la` and paste the content here.**

total 0
drwxrwxrwx 1 adharsh adharsh 4096 Sep  4 14:55 .
drwxrwxrwx 1 adharsh adharsh 4096 Sep  4 14:56 ..
-rwxrwxrwx 1 adharsh adharsh   98 Sep  4 14:55 .catkin_workspace
-rwxrwxrwx 1 adharsh adharsh    0 Sep  4 14:55 .gitkeep
drwxrwxrwx 1 adharsh adharsh 4096 Sep  4 14:56 src

6. **On your host, execute `docker images` and paste the content here.**

xauth:  file /home/adharsh/.Xauthority does not exist
GPUs: none

Starting container ...
  Name: ros
  Image: rwthika/acdc:latest

find: ‘/proc/28/task/28/fdinfo/5’: No such file or directory
find: ‘/proc/28/fdinfo/6’: No such file or directory
The container is running.

Execute the run script again from another terminal to open a shell in the container.
Alternatively, the container could have been launched with '-a' to attach directly.
Press Ctrl+Z followed and issue 'bg' to put this process into the background.
Press Ctrl+C to stop the container.

7. **Briefly explain your problem here. The explanation should contain a description of the expected behavior and the actual behavior.**

I followed all the steps and everything is working as usual except rqt and rviz. 
Expected behavior: Display a new window for rqt and rviz

Actual behavior: Did not get a new window and I got an error message attached below

8. **If you got an error message, paste it here or post a screenshot of it.**

**Error Message:**
qt.qpa.xcb: could not connect to display :0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

Aborted

**Screenshot:**
![error_rviz](https://github.com/ika-rwth-aachen/acdc/assets/18587740/4e526c03-a687-4ada-bb74-1b10ecd81e40)

**Comment by TillBeemelmanns** [comment]
Hi,

this is similar to https://github.com/ika-rwth-aachen/acdc/issues/6

Could you please try some of the suggestions here ?

- https://askubuntu.com/questions/1449804/wsl-when-i-try-to-use-gui-package-get-error-cant-open-display
- https://stackoverflow.com/questions/61110603/how-to-set-up-working-x11-forwarding-on-wsl2

Bests,
Till

**Comment by TillBeemelmanns** [comment]
Closed due to inactivity. Feel free to reopen if necessary.
